spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shpswfw?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
